
backend:
  name: git-gateway
  branch: main

media_folder: public/content
public_folder: /content

locale: 'cs'

slug:
  clean_accents: true

collections:
  - name: "Reference" # Used in routes, e.g., /admin/collections/blog
    label: "Reference" # Used in the UI
    folder: "references" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}