
backend:
  name: git-gateway
  branch: main

media_folder: public/content
public_folder: /content

locale: 'cs'

slug:
  clean_accents: true

collections:
  - name: "reference" # Used in routes, e.g., /admin/collections/blog
    label: "Reference" # Used in the UI
    folder: "/content/references" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Název", name: "title", widget: "string"}
      - {label: "Přední fotografie", name: "frontImg", widget: "image"}
      - {label: "Další fotografie", name: "secondImg", widget: "image", required: false}
      - {label: "Popis", name: "body", widget: "markdown"}

  - name: "documents" # Used in routes, e.g., /admin/collections/blog
    label: "Dokumenty" # Used in the UI
    folder: "/content/documents" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Název", name: "title", widget: "string"}
      - {
        label: "Soubory",
        name: "documentFiles",
        widget: "list",
        summary: '{{fields.image}}',
        field: {label: Image, name: image, widget: image}
      }

      