<template>
    <div>
        <NavbarTop/>
        <NavbarMain/>
        <Header/>
        <main>
            <SectionsAbout/>
            <SectionsHow/>
            <SectionsBenefits/>
            <SectionsGuaranty/>
        </main>
    </div>
</template>